-- Community volunteer roster + dua bots schema (admin-managed)

CREATE TABLE IF NOT EXISTS public.community_volunteers (
  user_id uuid PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  email text NOT NULL DEFAULT '',
  name text NOT NULL DEFAULT '',
  tier text NOT NULL DEFAULT 'helper'
    CHECK (tier IN ('helper', 'supervisor', 'manager')),
  status text NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'suspended')),
  notes text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS community_volunteers_status_tier_idx
  ON public.community_volunteers (status, tier);

ALTER TABLE public.community_volunteers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS community_volunteers_select ON public.community_volunteers;
CREATE POLICY community_volunteers_select ON public.community_volunteers
  FOR SELECT TO authenticated
  USING (
    user_id = auth.uid()
    OR public.is_super_admin()
  );

DROP POLICY IF EXISTS community_volunteers_admin_write ON public.community_volunteers;
CREATE POLICY community_volunteers_admin_write ON public.community_volunteers
  FOR ALL TO authenticated
  USING (public.is_super_admin())
  WITH CHECK (public.is_super_admin());

CREATE TABLE IF NOT EXISTS public.dua_bots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL CHECK (char_length(name) BETWEEN 2 AND 80),
  description text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'paused' CHECK (status IN ('active', 'paused')),
  frequency_minutes integer NOT NULL DEFAULT 360 CHECK (frequency_minutes BETWEEN 15 AND 10080),
  source_type text NOT NULL DEFAULT 'rss' CHECK (source_type IN ('rss')),
  rss_urls text[] NOT NULL DEFAULT '{}',
  keywords text[] NOT NULL DEFAULT '{}',
  categories text[] NOT NULL DEFAULT '{}',
  tone text NOT NULL DEFAULT 'compassionate' CHECK (char_length(tone) BETWEEN 2 AND 80),
  language text NOT NULL DEFAULT 'English' CHECK (char_length(language) BETWEEN 2 AND 80),
  system_prompt text NOT NULL DEFAULT '',
  max_duas_per_run integer NOT NULL DEFAULT 3 CHECK (max_duas_per_run BETWEEN 1 AND 20),
  target_category_id bigint REFERENCES public.categories (id) ON DELETE SET NULL,
  publish_mode text NOT NULL DEFAULT 'pending' CHECK (publish_mode IN ('pending', 'published')),
  last_run_at timestamptz,
  next_run_at timestamptz,
  last_status text NOT NULL DEFAULT 'never_run'
    CHECK (last_status IN ('never_run', 'success', 'error', 'skipped')),
  last_error text,
  created_by uuid REFERENCES auth.users (id) ON DELETE SET NULL,
  updated_by uuid REFERENCES auth.users (id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS dua_bots_status_next_run_idx
  ON public.dua_bots (status, next_run_at);

CREATE TABLE IF NOT EXISTS public.dua_bot_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bot_id bigint NOT NULL REFERENCES public.dua_bots (id) ON DELETE CASCADE,
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  status text NOT NULL DEFAULT 'running'
    CHECK (status IN ('running', 'success', 'error', 'skipped')),
  events_found integer NOT NULL DEFAULT 0 CHECK (events_found >= 0),
  duas_created integer NOT NULL DEFAULT 0 CHECK (duas_created >= 0),
  message text
);

CREATE INDEX IF NOT EXISTS dua_bot_runs_bot_started_idx
  ON public.dua_bot_runs (bot_id, started_at DESC);

CREATE TABLE IF NOT EXISTS public.dua_bot_event_posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bot_id bigint NOT NULL REFERENCES public.dua_bots (id) ON DELETE CASCADE,
  run_id bigint REFERENCES public.dua_bot_runs (id) ON DELETE SET NULL,
  dua_id bigint REFERENCES public.duas (id) ON DELETE SET NULL,
  event_key text NOT NULL,
  event_title text NOT NULL,
  event_url text,
  event_published_at timestamptz,
  source_type text NOT NULL DEFAULT 'rss',
  source_url text,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (bot_id, event_key)
);

ALTER TABLE public.dua_bots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dua_bot_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dua_bot_event_posts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS dua_bots_admin_all ON public.dua_bots;
CREATE POLICY dua_bots_admin_all ON public.dua_bots
  FOR ALL TO authenticated
  USING (public.is_super_admin())
  WITH CHECK (public.is_super_admin());

DROP POLICY IF EXISTS dua_bot_runs_admin_all ON public.dua_bot_runs;
CREATE POLICY dua_bot_runs_admin_all ON public.dua_bot_runs
  FOR ALL TO authenticated
  USING (public.is_super_admin())
  WITH CHECK (public.is_super_admin());

DROP POLICY IF EXISTS dua_bot_event_posts_admin_all ON public.dua_bot_event_posts;
CREATE POLICY dua_bot_event_posts_admin_all ON public.dua_bot_event_posts
  FOR ALL TO authenticated
  USING (public.is_super_admin())
  WITH CHECK (public.is_super_admin());

-- Form registries + footer links seeds
INSERT INTO public.site_settings (key, value)
VALUES
  ('footer.links', '[]'),
  ('channel_form.fields', ''),
  ('volunteer_form.fields', '')
ON CONFLICT (key) DO NOTHING;
