-- Channel applications, volunteers, and public site_settings whitelist

ALTER TABLE public.categories
  ADD COLUMN IF NOT EXISTS application jsonb NOT NULL DEFAULT '{}'::jsonb;

CREATE UNIQUE INDEX IF NOT EXISTS categories_one_pending_application_per_owner
  ON public.categories (owner_id)
  WHERE channel_type = 'user'
    AND status = 'pending_review'
    AND owner_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.volunteer_applications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users (id) ON DELETE SET NULL,
  email text NOT NULL,
  name text NOT NULL DEFAULT '',
  message text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'rejected')),
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  reviewed_at timestamptz,
  reviewed_by uuid REFERENCES auth.users (id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS volunteer_applications_status_idx
  ON public.volunteer_applications (status, created_at DESC);

ALTER TABLE public.volunteer_applications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS volunteer_applications_select_own ON public.volunteer_applications;
CREATE POLICY volunteer_applications_select_own ON public.volunteer_applications
  FOR SELECT TO authenticated
  USING (
    user_id = auth.uid()
    OR public.is_super_admin()
  );

-- site_settings: allow reading non-secret product keys
DROP POLICY IF EXISTS site_settings_select_public ON public.site_settings;
CREATE POLICY site_settings_select_public ON public.site_settings
  FOR SELECT TO anon, authenticated
  USING (
    public.is_super_admin()
    OR key = 'posting.mode'
    OR key = 'rss.enabled'
    OR key = 'rss.item_count'
    OR key LIKE 'copy.%'
    OR key = 'ai_moderation.enabled'
  );

INSERT INTO public.site_settings (key, value)
VALUES
  ('rss.enabled', 'false'),
  ('rss.item_count', '25'),
  ('ai_moderation.enabled', 'false')
ON CONFLICT (key) DO NOTHING;
