-- DuaPrayer community domain (feed, share dua, ameen)
-- Coexists with Makerkit accounts; uses public.is_super_admin() for elevated reads.

-- Categories (topics now; channel columns reserved for later port)
CREATE TABLE IF NOT EXISTS public.categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  description text NOT NULL DEFAULT '',
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  channel_type text NOT NULL DEFAULT 'category'
    CHECK (channel_type IN ('category', 'user')),
  status text NOT NULL DEFAULT 'approved'
    CHECK (status IN ('approved', 'pending_review', 'rejected')),
  owner_id uuid REFERENCES auth.users (id) ON DELETE SET NULL,
  handle text UNIQUE,
  is_verified boolean NOT NULL DEFAULT false,
  verified_at timestamptz,
  reviewed_at timestamptz,
  reviewed_by uuid REFERENCES auth.users (id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS categories_active_status_idx
  ON public.categories (is_active, status, sort_order, name);

-- Duas
CREATE TABLE IF NOT EXISTS public.duas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text text NOT NULL CHECK (char_length(text) >= 15 AND char_length(text) <= 1200),
  user_id uuid REFERENCES auth.users (id) ON DELETE SET NULL,
  category_id bigint REFERENCES public.categories (id) ON DELETE SET NULL,
  channel_id bigint REFERENCES public.categories (id) ON DELETE SET NULL,
  likes integer NOT NULL DEFAULT 0 CHECK (likes >= 0),
  published boolean NOT NULL DEFAULT true,
  flagged boolean NOT NULL DEFAULT false,
  language text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS duas_published_created_idx
  ON public.duas (published, created_at DESC);

CREATE INDEX IF NOT EXISTS duas_category_idx ON public.duas (category_id);

CREATE INDEX IF NOT EXISTS duas_channel_idx ON public.duas (channel_id);

CREATE INDEX IF NOT EXISTS duas_flagged_idx ON public.duas (flagged)
  WHERE flagged = true;

-- Ameen / prayer dedupe
CREATE TABLE IF NOT EXISTS public.dua_prayers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dua_id bigint NOT NULL REFERENCES public.duas (id) ON DELETE CASCADE,
  user_id uuid REFERENCES auth.users (id) ON DELETE CASCADE,
  voter_hash text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT dua_prayers_voter_check CHECK (
    user_id IS NOT NULL
    OR voter_hash IS NOT NULL
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS dua_prayers_user_unique
  ON public.dua_prayers (dua_id, user_id)
  WHERE user_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS dua_prayers_hash_unique
  ON public.dua_prayers (dua_id, voter_hash)
  WHERE voter_hash IS NOT NULL;

CREATE INDEX IF NOT EXISTS dua_prayers_user_id_idx ON public.dua_prayers (user_id);

CREATE INDEX IF NOT EXISTS dua_prayers_voter_hash_idx ON public.dua_prayers (voter_hash);

-- Seed topic categories
INSERT INTO public.categories (name, channel_type, status, is_verified, sort_order)
VALUES
  ('General', 'category', 'approved', true, 10),
  ('Health', 'category', 'approved', true, 20),
  ('Family', 'category', 'approved', true, 30),
  ('Guidance', 'category', 'approved', true, 40),
  ('Forgiveness', 'category', 'approved', true, 50),
  ('Gratitude', 'category', 'approved', true, 60),
  ('Protection', 'category', 'approved', true, 70),
  ('Community', 'category', 'approved', true, 80)
ON CONFLICT (name) DO NOTHING;

-- Ameen RPC
CREATE OR REPLACE FUNCTION public.pray_for_dua (
  p_dua_id bigint,
  p_voter_hash text DEFAULT NULL
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id uuid := auth.uid();
  v_hash text;
  v_inserted boolean := false;
BEGIN
  IF p_dua_id IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'invalid_dua');
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.duas
    WHERE id = p_dua_id
      AND published = true
  ) THEN
    RETURN jsonb_build_object('success', false, 'error', 'not_found');
  END IF;

  IF v_user_id IS NOT NULL THEN
    INSERT INTO public.dua_prayers (dua_id, user_id)
    VALUES (p_dua_id, v_user_id)
    ON CONFLICT DO NOTHING;

    GET DIAGNOSTICS v_inserted = ROW_COUNT;

    IF v_inserted THEN
      UPDATE public.duas
      SET likes = likes + 1
      WHERE id = p_dua_id;
    END IF;
  ELSIF p_voter_hash IS NOT NULL AND length(p_voter_hash) >= 16 THEN
    v_hash := p_voter_hash;

    INSERT INTO public.dua_prayers (dua_id, voter_hash)
    VALUES (p_dua_id, v_hash)
    ON CONFLICT DO NOTHING;

    GET DIAGNOSTICS v_inserted = ROW_COUNT;

    IF v_inserted THEN
      UPDATE public.duas
      SET likes = likes + 1
      WHERE id = p_dua_id;
    END IF;
  ELSE
    RETURN jsonb_build_object('success', false, 'error', 'unauthorized');
  END IF;

  RETURN jsonb_build_object(
    'success', true,
    'counted', v_inserted,
    'likes', (SELECT likes FROM public.duas WHERE id = p_dua_id)
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.pray_for_dua (bigint, text) TO anon, authenticated, service_role;

-- RLS
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.duas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dua_prayers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS categories_select_approved ON public.categories;
CREATE POLICY categories_select_approved ON public.categories
  FOR SELECT TO anon, authenticated
  USING (
    status = 'approved'
    OR public.is_super_admin()
  );

DROP POLICY IF EXISTS duas_select_published ON public.duas;
CREATE POLICY duas_select_published ON public.duas
  FOR SELECT TO anon, authenticated
  USING (
    published = true
    OR public.is_super_admin()
  );

DROP POLICY IF EXISTS dua_prayers_select_own ON public.dua_prayers;
CREATE POLICY dua_prayers_select_own ON public.dua_prayers
  FOR SELECT TO authenticated
  USING (
    user_id = auth.uid()
    OR public.is_super_admin()
  );

-- No INSERT/UPDATE/DELETE policies on duas: app uses service-role client.
GRANT SELECT ON public.categories TO anon, authenticated;
GRANT SELECT ON public.duas TO anon, authenticated;
GRANT SELECT ON public.dua_prayers TO authenticated;
