-- Extended DuaPrayer community: follows, bookmarks, flags, site_settings

CREATE TABLE IF NOT EXISTS public.user_follows (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  channel_id bigint NOT NULL REFERENCES public.categories (id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, channel_id)
);

CREATE INDEX IF NOT EXISTS user_follows_user_id_idx ON public.user_follows (user_id);
CREATE INDEX IF NOT EXISTS user_follows_channel_id_idx ON public.user_follows (channel_id);

CREATE TABLE IF NOT EXISTS public.bookmarks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  dua_id bigint NOT NULL REFERENCES public.duas (id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, dua_id)
);

CREATE INDEX IF NOT EXISTS bookmarks_user_id_idx ON public.bookmarks (user_id);

CREATE TABLE IF NOT EXISTS public.dua_flags (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dua_id bigint NOT NULL REFERENCES public.duas (id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (dua_id, user_id)
);

CREATE INDEX IF NOT EXISTS dua_flags_dua_id_idx ON public.dua_flags (dua_id);

CREATE TABLE IF NOT EXISTS public.site_settings (
  key text PRIMARY KEY,
  value text NOT NULL DEFAULT '',
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.site_settings (key, value)
VALUES ('posting.mode', 'public')
ON CONFLICT (key) DO NOTHING;

ALTER TABLE public.user_follows ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookmarks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dua_flags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS user_follows_select_own ON public.user_follows;
CREATE POLICY user_follows_select_own ON public.user_follows
  FOR SELECT TO authenticated
  USING (user_id = auth.uid() OR public.is_super_admin());

DROP POLICY IF EXISTS user_follows_insert_own ON public.user_follows;
CREATE POLICY user_follows_insert_own ON public.user_follows
  FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS user_follows_delete_own ON public.user_follows;
CREATE POLICY user_follows_delete_own ON public.user_follows
  FOR DELETE TO authenticated
  USING (user_id = auth.uid());

-- bookmarks / flags / site_settings: service-role writes from app actions
DROP POLICY IF EXISTS site_settings_select_public ON public.site_settings;
CREATE POLICY site_settings_select_public ON public.site_settings
  FOR SELECT TO anon, authenticated
  USING (key = 'posting.mode' OR public.is_super_admin());

GRANT SELECT, INSERT, DELETE ON public.user_follows TO authenticated;
GRANT SELECT ON public.site_settings TO anon, authenticated;
