-- DuaPrayer production schema
-- Apply via Supabase Dashboard → SQL Editor, or: supabase db push

-- Categories
CREATE TABLE IF NOT EXISTS public.categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Profiles (admin flag in app_metadata-safe column)
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  display_name text,
  is_admin boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Upgrade existing duas table from prototype
ALTER TABLE IF EXISTS public.duas ADD COLUMN IF NOT EXISTS published boolean NOT NULL DEFAULT true;
ALTER TABLE IF EXISTS public.duas ADD COLUMN IF NOT EXISTS flagged boolean NOT NULL DEFAULT false;

-- Duas
CREATE TABLE IF NOT EXISTS public.duas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text text NOT NULL CHECK (char_length(text) >= 15 AND char_length(text) <= 280),
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  category_id bigint REFERENCES public.categories(id) ON DELETE SET NULL,
  likes integer NOT NULL DEFAULT 0 CHECK (likes >= 0),
  published boolean NOT NULL DEFAULT true,
  flagged boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS duas_published_created_idx ON public.duas (published, created_at DESC);
CREATE INDEX IF NOT EXISTS duas_flagged_idx ON public.duas (flagged) WHERE flagged = true;
CREATE INDEX IF NOT EXISTS duas_category_idx ON public.duas (category_id);

-- Anonymous + authenticated pray deduplication
CREATE TABLE IF NOT EXISTS public.dua_prayers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dua_id bigint NOT NULL REFERENCES public.duas(id) ON DELETE CASCADE,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  voter_hash text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT dua_prayers_voter_check CHECK (user_id IS NOT NULL OR voter_hash IS NOT NULL)
);

CREATE UNIQUE INDEX IF NOT EXISTS dua_prayers_user_unique ON public.dua_prayers (dua_id, user_id) WHERE user_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS dua_prayers_hash_unique ON public.dua_prayers (dua_id, voter_hash) WHERE voter_hash IS NOT NULL;

-- Seed categories
INSERT INTO public.categories (name) VALUES
  ('General'),
  ('Health'),
  ('Family'),
  ('Guidance'),
  ('Forgiveness'),
  ('Gratitude'),
  ('Protection'),
  ('Community')
ON CONFLICT (name) DO NOTHING;

-- Auto-create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, display_name)
  VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data->>'display_name', split_part(NEW.email, '@', 1)))
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Pray RPC: dedupe via dua_prayers, increment likes
CREATE OR REPLACE FUNCTION public.pray_for_dua(p_dua_id bigint, p_voter_hash text DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id uuid := auth.uid();
  v_hash text;
  v_inserted boolean := false;
BEGIN
  IF p_dua_id IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'invalid_dua');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.duas WHERE id = p_dua_id AND published = true) THEN
    RETURN jsonb_build_object('success', false, 'error', 'not_found');
  END IF;

  IF v_user_id IS NOT NULL THEN
    INSERT INTO public.dua_prayers (dua_id, user_id)
    VALUES (p_dua_id, v_user_id)
    ON CONFLICT DO NOTHING;
    GET DIAGNOSTICS v_inserted = ROW_COUNT;
    IF v_inserted THEN
      UPDATE public.duas SET likes = likes + 1 WHERE id = p_dua_id;
    END IF;
  ELSIF p_voter_hash IS NOT NULL AND length(p_voter_hash) >= 16 THEN
    v_hash := p_voter_hash;
    INSERT INTO public.dua_prayers (dua_id, voter_hash)
    VALUES (p_dua_id, v_hash)
    ON CONFLICT DO NOTHING;
    GET DIAGNOSTICS v_inserted = ROW_COUNT;
    IF v_inserted THEN
      UPDATE public.duas SET likes = likes + 1 WHERE id = p_dua_id;
    END IF;
  ELSE
    RETURN jsonb_build_object('success', false, 'error', 'unauthorized');
  END IF;

  RETURN jsonb_build_object(
    'success', true,
    'counted', v_inserted,
    'likes', (SELECT likes FROM public.duas WHERE id = p_dua_id)
  );
END;
$$;

-- Legacy RPC name used by prototype
CREATE OR REPLACE FUNCTION public.increment_likes(dua_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  PERFORM public.pray_for_dua(dua_id, NULL);
END;
$$;

-- RLS
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.duas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dua_prayers ENABLE ROW LEVEL SECURITY;

-- Helper: is admin
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE(
    (SELECT is_admin FROM public.profiles WHERE id = auth.uid()),
    false
  );
$$;

-- Categories: public read
DROP POLICY IF EXISTS categories_select ON public.categories;
CREATE POLICY categories_select ON public.categories FOR SELECT TO anon, authenticated USING (true);

-- Profiles
DROP POLICY IF EXISTS profiles_select_own ON public.profiles;
CREATE POLICY profiles_select_own ON public.profiles FOR SELECT TO authenticated
  USING (id = auth.uid() OR public.is_admin());

DROP POLICY IF EXISTS profiles_update_own ON public.profiles;
CREATE POLICY profiles_update_own ON public.profiles FOR UPDATE TO authenticated
  USING (id = auth.uid()) WITH CHECK (id = auth.uid());

-- Duas: public read published only
DROP POLICY IF EXISTS duas_select_published ON public.duas;
CREATE POLICY duas_select_published ON public.duas FOR SELECT TO anon, authenticated
  USING (published = true OR public.is_admin());

-- Dua prayers: users read own
DROP POLICY IF EXISTS dua_prayers_select_own ON public.dua_prayers;
CREATE POLICY dua_prayers_select_own ON public.dua_prayers FOR SELECT TO authenticated
  USING (user_id = auth.uid() OR public.is_admin());

-- Grant execute on RPCs
GRANT EXECUTE ON FUNCTION public.pray_for_dua(bigint, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.increment_likes(bigint) TO anon, authenticated;
